test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

pos:
  resource:  "@POSBundle/Resources/config/routing.yml"
  prefix: /
