TestBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: TestBundle\Repository\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 100

    manyToOne:
        task:
            targetEntity: Task
            inversedBy: Tag
            joinColumn:
              name: task_id
              referencedColumnName: id

    lifecycleCallbacks: {  }
