TestBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: TestBundle\Repository\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
