app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

hello:
  path: /hello/{name}
  defaults: { _controller: AppBundle:Hello:index }