app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

app_form:
    path: /form
    defaults: { _controller: AppBundle:Task:new}

hello:
  path: /hello/{name}
  defaults: { _controller: AppBundle:Hello:index }

create_product:
  path: /create_product
  defaults: { _controller: AppBundle:Default:create }