pos_homepage:
    path:     /
    defaults: { _controller: POSBundle:Default:index }

front_display:
    path:     /test
    defaults: { _controller: POSBundle:FrontDisplay:message }

pos_admin:
    path:   /admin/items
    defaults: { _controller: POSBundle:POSAdmin:manageItem }

